#!/usr/bin/env npx tsx
/**
 * Generate Photon-compatible JSON for top 1000+ world cities by population.
 *
 * Usage: npx tsx scripts/generate-top-cities-json.ts [existing-cities.json] > top-cities.json
 */

const PHOTON_URL = 'https://photon.komoot.io/api';
const RATE_LIMIT_MS = 1100; // ~1 request per second

// Top 1000+ world cities by population/importance
// Sourced from major world city lists
const TOP_CITIES: Array<{ city: string; country: string }> = [
  // ASIA - Major Cities
  { city: 'Tokyo', country: 'Japan' },
  { city: 'Delhi', country: 'India' },
  { city: 'Shanghai', country: 'China' },
  { city: 'Beijing', country: 'China' },
  { city: 'Mumbai', country: 'India' },
  { city: 'Osaka', country: 'Japan' },
  { city: 'Dhaka', country: 'Bangladesh' },
  { city: 'Karachi', country: 'Pakistan' },
  { city: 'Kolkata', country: 'India' },
  { city: 'Chongqing', country: 'China' },
  { city: 'Guangzhou', country: 'China' },
  { city: 'Manila', country: 'Philippines' },
  { city: 'Tianjin', country: 'China' },
  { city: 'Shenzhen', country: 'China' },
  { city: 'Bangalore', country: 'India' },
  { city: 'Jakarta', country: 'Indonesia' },
  { city: 'Chennai', country: 'India' },
  { city: 'Seoul', country: 'South Korea' },
  { city: 'Hyderabad', country: 'India' },
  { city: 'Bangkok', country: 'Thailand' },
  { city: 'Lahore', country: 'Pakistan' },
  { city: 'Chengdu', country: 'China' },
  { city: 'Nanjing', country: 'China' },
  { city: 'Wuhan', country: 'China' },
  { city: 'Ho Chi Minh City', country: 'Vietnam' },
  { city: 'Hanoi', country: 'Vietnam' },
  { city: 'Hong Kong', country: 'China' },
  { city: 'Ahmedabad', country: 'India' },
  { city: 'Kuala Lumpur', country: 'Malaysia' },
  { city: 'Singapore', country: 'Singapore' },
  { city: 'Xi\'an', country: 'China' },
  { city: 'Surat', country: 'India' },
  { city: 'Pune', country: 'India' },
  { city: 'Yangon', country: 'Myanmar' },
  { city: 'Jaipur', country: 'India' },
  { city: 'Busan', country: 'South Korea' },
  { city: 'Lucknow', country: 'India' },
  { city: 'Surabaya', country: 'Indonesia' },
  { city: 'Kanpur', country: 'India' },
  { city: 'Taipei', country: 'Taiwan' },
  { city: 'Nagoya', country: 'Japan' },
  { city: 'Jeddah', country: 'Saudi Arabia' },
  { city: 'Riyadh', country: 'Saudi Arabia' },
  { city: 'Dubai', country: 'United Arab Emirates' },
  { city: 'Abu Dhabi', country: 'United Arab Emirates' },
  { city: 'Doha', country: 'Qatar' },
  { city: 'Kuwait City', country: 'Kuwait' },
  { city: 'Tel Aviv', country: 'Israel' },
  { city: 'Jerusalem', country: 'Israel' },
  { city: 'Amman', country: 'Jordan' },
  { city: 'Beirut', country: 'Lebanon' },
  { city: 'Nagpur', country: 'India' },
  { city: 'Indore', country: 'India' },
  { city: 'Bhopal', country: 'India' },
  { city: 'Patna', country: 'India' },
  { city: 'Vadodara', country: 'India' },
  { city: 'Sapporo', country: 'Japan' },
  { city: 'Kyoto', country: 'Japan' },
  { city: 'Fukuoka', country: 'Japan' },
  { city: 'Kobe', country: 'Japan' },
  { city: 'Kawasaki', country: 'Japan' },
  { city: 'Saitama', country: 'Japan' },
  { city: 'Hiroshima', country: 'Japan' },
  { city: 'Sendai', country: 'Japan' },
  { city: 'Incheon', country: 'South Korea' },
  { city: 'Daegu', country: 'South Korea' },
  { city: 'Daejeon', country: 'South Korea' },
  { city: 'Gwangju', country: 'South Korea' },
  { city: 'Kaohsiung', country: 'Taiwan' },
  { city: 'Taichung', country: 'Taiwan' },
  { city: 'Tainan', country: 'Taiwan' },
  { city: 'Bandung', country: 'Indonesia' },
  { city: 'Medan', country: 'Indonesia' },
  { city: 'Makassar', country: 'Indonesia' },
  { city: 'Cebu City', country: 'Philippines' },
  { city: 'Quezon City', country: 'Philippines' },
  { city: 'Davao City', country: 'Philippines' },
  { city: 'Phnom Penh', country: 'Cambodia' },
  { city: 'Vientiane', country: 'Laos' },
  { city: 'Chittagong', country: 'Bangladesh' },
  { city: 'Faisalabad', country: 'Pakistan' },
  { city: 'Rawalpindi', country: 'Pakistan' },
  { city: 'Islamabad', country: 'Pakistan' },
  { city: 'Peshawar', country: 'Pakistan' },
  { city: 'Quetta', country: 'Pakistan' },
  { city: 'Kathmandu', country: 'Nepal' },
  { city: 'Colombo', country: 'Sri Lanka' },
  { city: 'Almaty', country: 'Kazakhstan' },
  { city: 'Astana', country: 'Kazakhstan' },
  { city: 'Tashkent', country: 'Uzbekistan' },
  { city: 'Baku', country: 'Azerbaijan' },
  { city: 'Tbilisi', country: 'Georgia' },
  { city: 'Yerevan', country: 'Armenia' },
  { city: 'Ulaanbaatar', country: 'Mongolia' },

  // EUROPE - Major Cities
  { city: 'London', country: 'United Kingdom' },
  { city: 'Paris', country: 'France' },
  { city: 'Berlin', country: 'Germany' },
  { city: 'Madrid', country: 'Spain' },
  { city: 'Rome', country: 'Italy' },
  { city: 'Moscow', country: 'Russia' },
  { city: 'Saint Petersburg', country: 'Russia' },
  { city: 'Istanbul', country: 'Turkey' },
  { city: 'Ankara', country: 'Turkey' },
  { city: 'Kyiv', country: 'Ukraine' },
  { city: 'Barcelona', country: 'Spain' },
  { city: 'Milan', country: 'Italy' },
  { city: 'Munich', country: 'Germany' },
  { city: 'Amsterdam', country: 'Netherlands' },
  { city: 'Vienna', country: 'Austria' },
  { city: 'Warsaw', country: 'Poland' },
  { city: 'Budapest', country: 'Hungary' },
  { city: 'Prague', country: 'Czech Republic' },
  { city: 'Brussels', country: 'Belgium' },
  { city: 'Stockholm', country: 'Sweden' },
  { city: 'Copenhagen', country: 'Denmark' },
  { city: 'Oslo', country: 'Norway' },
  { city: 'Helsinki', country: 'Finland' },
  { city: 'Dublin', country: 'Ireland' },
  { city: 'Lisbon', country: 'Portugal' },
  { city: 'Athens', country: 'Greece' },
  { city: 'Zurich', country: 'Switzerland' },
  { city: 'Geneva', country: 'Switzerland' },
  { city: 'Edinburgh', country: 'United Kingdom' },
  { city: 'Manchester', country: 'United Kingdom' },
  { city: 'Birmingham', country: 'United Kingdom' },
  { city: 'Glasgow', country: 'United Kingdom' },
  { city: 'Liverpool', country: 'United Kingdom' },
  { city: 'Leeds', country: 'United Kingdom' },
  { city: 'Bristol', country: 'United Kingdom' },
  { city: 'Sheffield', country: 'United Kingdom' },
  { city: 'Newcastle', country: 'United Kingdom' },
  { city: 'Belfast', country: 'United Kingdom' },
  { city: 'Cardiff', country: 'United Kingdom' },
  { city: 'Lyon', country: 'France' },
  { city: 'Marseille', country: 'France' },
  { city: 'Toulouse', country: 'France' },
  { city: 'Nice', country: 'France' },
  { city: 'Nantes', country: 'France' },
  { city: 'Strasbourg', country: 'France' },
  { city: 'Montpellier', country: 'France' },
  { city: 'Bordeaux', country: 'France' },
  { city: 'Lille', country: 'France' },
  { city: 'Hamburg', country: 'Germany' },
  { city: 'Frankfurt', country: 'Germany' },
  { city: 'Cologne', country: 'Germany' },
  { city: 'Stuttgart', country: 'Germany' },
  { city: 'Dusseldorf', country: 'Germany' },
  { city: 'Dortmund', country: 'Germany' },
  { city: 'Essen', country: 'Germany' },
  { city: 'Leipzig', country: 'Germany' },
  { city: 'Bremen', country: 'Germany' },
  { city: 'Dresden', country: 'Germany' },
  { city: 'Hanover', country: 'Germany' },
  { city: 'Nuremberg', country: 'Germany' },
  { city: 'Naples', country: 'Italy' },
  { city: 'Turin', country: 'Italy' },
  { city: 'Florence', country: 'Italy' },
  { city: 'Palermo', country: 'Italy' },
  { city: 'Genoa', country: 'Italy' },
  { city: 'Bologna', country: 'Italy' },
  { city: 'Venice', country: 'Italy' },
  { city: 'Valencia', country: 'Spain' },
  { city: 'Seville', country: 'Spain' },
  { city: 'Zaragoza', country: 'Spain' },
  { city: 'Malaga', country: 'Spain' },
  { city: 'Bilbao', country: 'Spain' },
  { city: 'Krakow', country: 'Poland' },
  { city: 'Lodz', country: 'Poland' },
  { city: 'Wroclaw', country: 'Poland' },
  { city: 'Poznan', country: 'Poland' },
  { city: 'Gdansk', country: 'Poland' },
  { city: 'Bucharest', country: 'Romania' },
  { city: 'Cluj-Napoca', country: 'Romania' },
  { city: 'Sofia', country: 'Bulgaria' },
  { city: 'Zagreb', country: 'Croatia' },
  { city: 'Belgrade', country: 'Serbia' },
  { city: 'Ljubljana', country: 'Slovenia' },
  { city: 'Bratislava', country: 'Slovakia' },
  { city: 'Riga', country: 'Latvia' },
  { city: 'Vilnius', country: 'Lithuania' },
  { city: 'Tallinn', country: 'Estonia' },
  { city: 'Minsk', country: 'Belarus' },
  { city: 'Chisinau', country: 'Moldova' },
  { city: 'Sarajevo', country: 'Bosnia and Herzegovina' },
  { city: 'Skopje', country: 'North Macedonia' },
  { city: 'Tirana', country: 'Albania' },
  { city: 'Podgorica', country: 'Montenegro' },
  { city: 'Pristina', country: 'Kosovo' },
  { city: 'Rotterdam', country: 'Netherlands' },
  { city: 'The Hague', country: 'Netherlands' },
  { city: 'Utrecht', country: 'Netherlands' },
  { city: 'Eindhoven', country: 'Netherlands' },
  { city: 'Antwerp', country: 'Belgium' },
  { city: 'Ghent', country: 'Belgium' },
  { city: 'Salzburg', country: 'Austria' },
  { city: 'Innsbruck', country: 'Austria' },
  { city: 'Graz', country: 'Austria' },
  { city: 'Gothenburg', country: 'Sweden' },
  { city: 'Malmo', country: 'Sweden' },
  { city: 'Aarhus', country: 'Denmark' },
  { city: 'Bergen', country: 'Norway' },
  { city: 'Tampere', country: 'Finland' },
  { city: 'Turku', country: 'Finland' },
  { city: 'Porto', country: 'Portugal' },
  { city: 'Thessaloniki', country: 'Greece' },
  { city: 'Basel', country: 'Switzerland' },
  { city: 'Bern', country: 'Switzerland' },
  { city: 'Lausanne', country: 'Switzerland' },
  { city: 'Luxembourg City', country: 'Luxembourg' },
  { city: 'Monaco', country: 'Monaco' },
  { city: 'Reykjavik', country: 'Iceland' },
  { city: 'Cork', country: 'Ireland' },
  { city: 'Galway', country: 'Ireland' },
  { city: 'Valletta', country: 'Malta' },
  { city: 'Nicosia', country: 'Cyprus' },
  { city: 'Andorra la Vella', country: 'Andorra' },

  // NORTH AMERICA (non-US)
  { city: 'Toronto', country: 'Canada' },
  { city: 'Montreal', country: 'Canada' },
  { city: 'Vancouver', country: 'Canada' },
  { city: 'Calgary', country: 'Canada' },
  { city: 'Edmonton', country: 'Canada' },
  { city: 'Ottawa', country: 'Canada' },
  { city: 'Winnipeg', country: 'Canada' },
  { city: 'Quebec City', country: 'Canada' },
  { city: 'Hamilton', country: 'Canada' },
  { city: 'Kitchener', country: 'Canada' },
  { city: 'London', country: 'Canada' },
  { city: 'Victoria', country: 'Canada' },
  { city: 'Halifax', country: 'Canada' },
  { city: 'Saskatoon', country: 'Canada' },
  { city: 'Regina', country: 'Canada' },
  { city: 'Mexico City', country: 'Mexico' },
  { city: 'Guadalajara', country: 'Mexico' },
  { city: 'Monterrey', country: 'Mexico' },
  { city: 'Puebla', country: 'Mexico' },
  { city: 'Tijuana', country: 'Mexico' },
  { city: 'Leon', country: 'Mexico' },
  { city: 'Cancun', country: 'Mexico' },
  { city: 'Merida', country: 'Mexico' },
  { city: 'Havana', country: 'Cuba' },
  { city: 'Santo Domingo', country: 'Dominican Republic' },
  { city: 'San Juan', country: 'Puerto Rico' },
  { city: 'Port-au-Prince', country: 'Haiti' },
  { city: 'Kingston', country: 'Jamaica' },
  { city: 'Nassau', country: 'Bahamas' },
  { city: 'Guatemala City', country: 'Guatemala' },
  { city: 'San Salvador', country: 'El Salvador' },
  { city: 'Tegucigalpa', country: 'Honduras' },
  { city: 'Managua', country: 'Nicaragua' },
  { city: 'San Jose', country: 'Costa Rica' },
  { city: 'Panama City', country: 'Panama' },

  // SOUTH AMERICA
  { city: 'Sao Paulo', country: 'Brazil' },
  { city: 'Rio de Janeiro', country: 'Brazil' },
  { city: 'Buenos Aires', country: 'Argentina' },
  { city: 'Lima', country: 'Peru' },
  { city: 'Bogota', country: 'Colombia' },
  { city: 'Santiago', country: 'Chile' },
  { city: 'Caracas', country: 'Venezuela' },
  { city: 'Belo Horizonte', country: 'Brazil' },
  { city: 'Brasilia', country: 'Brazil' },
  { city: 'Salvador', country: 'Brazil' },
  { city: 'Fortaleza', country: 'Brazil' },
  { city: 'Curitiba', country: 'Brazil' },
  { city: 'Recife', country: 'Brazil' },
  { city: 'Porto Alegre', country: 'Brazil' },
  { city: 'Medellin', country: 'Colombia' },
  { city: 'Cali', country: 'Colombia' },
  { city: 'Barranquilla', country: 'Colombia' },
  { city: 'Cartagena', country: 'Colombia' },
  { city: 'Cordoba', country: 'Argentina' },
  { city: 'Rosario', country: 'Argentina' },
  { city: 'Mendoza', country: 'Argentina' },
  { city: 'Valparaiso', country: 'Chile' },
  { city: 'Concepcion', country: 'Chile' },
  { city: 'Quito', country: 'Ecuador' },
  { city: 'Guayaquil', country: 'Ecuador' },
  { city: 'La Paz', country: 'Bolivia' },
  { city: 'Santa Cruz', country: 'Bolivia' },
  { city: 'Asuncion', country: 'Paraguay' },
  { city: 'Montevideo', country: 'Uruguay' },
  { city: 'Georgetown', country: 'Guyana' },
  { city: 'Paramaribo', country: 'Suriname' },

  // AFRICA
  { city: 'Cairo', country: 'Egypt' },
  { city: 'Lagos', country: 'Nigeria' },
  { city: 'Kinshasa', country: 'Democratic Republic of the Congo' },
  { city: 'Johannesburg', country: 'South Africa' },
  { city: 'Luanda', country: 'Angola' },
  { city: 'Nairobi', country: 'Kenya' },
  { city: 'Casablanca', country: 'Morocco' },
  { city: 'Alexandria', country: 'Egypt' },
  { city: 'Addis Ababa', country: 'Ethiopia' },
  { city: 'Cape Town', country: 'South Africa' },
  { city: 'Abidjan', country: 'Ivory Coast' },
  { city: 'Khartoum', country: 'Sudan' },
  { city: 'Dar es Salaam', country: 'Tanzania' },
  { city: 'Accra', country: 'Ghana' },
  { city: 'Algiers', country: 'Algeria' },
  { city: 'Tunis', country: 'Tunisia' },
  { city: 'Dakar', country: 'Senegal' },
  { city: 'Durban', country: 'South Africa' },
  { city: 'Pretoria', country: 'South Africa' },
  { city: 'Kampala', country: 'Uganda' },
  { city: 'Lusaka', country: 'Zambia' },
  { city: 'Harare', country: 'Zimbabwe' },
  { city: 'Douala', country: 'Cameroon' },
  { city: 'Yaounde', country: 'Cameroon' },
  { city: 'Maputo', country: 'Mozambique' },
  { city: 'Rabat', country: 'Morocco' },
  { city: 'Marrakech', country: 'Morocco' },
  { city: 'Fes', country: 'Morocco' },
  { city: 'Tripoli', country: 'Libya' },
  { city: 'Abuja', country: 'Nigeria' },
  { city: 'Kano', country: 'Nigeria' },
  { city: 'Ibadan', country: 'Nigeria' },
  { city: 'Port Harcourt', country: 'Nigeria' },
  { city: 'Bamako', country: 'Mali' },
  { city: 'Ouagadougou', country: 'Burkina Faso' },
  { city: 'Conakry', country: 'Guinea' },
  { city: 'Lome', country: 'Togo' },
  { city: 'Cotonou', country: 'Benin' },
  { city: 'Niamey', country: 'Niger' },
  { city: 'Nouakchott', country: 'Mauritania' },
  { city: 'Freetown', country: 'Sierra Leone' },
  { city: 'Monrovia', country: 'Liberia' },
  { city: 'Banjul', country: 'Gambia' },
  { city: 'Bissau', country: 'Guinea-Bissau' },
  { city: 'Praia', country: 'Cape Verde' },
  { city: 'Asmara', country: 'Eritrea' },
  { city: 'Djibouti', country: 'Djibouti' },
  { city: 'Mogadishu', country: 'Somalia' },
  { city: 'Kigali', country: 'Rwanda' },
  { city: 'Bujumbura', country: 'Burundi' },
  { city: 'Lilongwe', country: 'Malawi' },
  { city: 'Gaborone', country: 'Botswana' },
  { city: 'Windhoek', country: 'Namibia' },
  { city: 'Mbabane', country: 'Eswatini' },
  { city: 'Maseru', country: 'Lesotho' },
  { city: 'Antananarivo', country: 'Madagascar' },
  { city: 'Port Louis', country: 'Mauritius' },
  { city: 'Victoria', country: 'Seychelles' },
  { city: 'Moroni', country: 'Comoros' },
  { city: 'Libreville', country: 'Gabon' },
  { city: 'Brazzaville', country: 'Republic of the Congo' },
  { city: 'Bangui', country: 'Central African Republic' },
  { city: 'Malabo', country: 'Equatorial Guinea' },
  { city: 'Sao Tome', country: 'Sao Tome and Principe' },
  { city: 'N\'Djamena', country: 'Chad' },
  { city: 'Juba', country: 'South Sudan' },

  // OCEANIA
  { city: 'Sydney', country: 'Australia' },
  { city: 'Melbourne', country: 'Australia' },
  { city: 'Brisbane', country: 'Australia' },
  { city: 'Perth', country: 'Australia' },
  { city: 'Adelaide', country: 'Australia' },
  { city: 'Gold Coast', country: 'Australia' },
  { city: 'Newcastle', country: 'Australia' },
  { city: 'Canberra', country: 'Australia' },
  { city: 'Hobart', country: 'Australia' },
  { city: 'Darwin', country: 'Australia' },
  { city: 'Auckland', country: 'New Zealand' },
  { city: 'Wellington', country: 'New Zealand' },
  { city: 'Christchurch', country: 'New Zealand' },
  { city: 'Hamilton', country: 'New Zealand' },
  { city: 'Dunedin', country: 'New Zealand' },
  { city: 'Suva', country: 'Fiji' },
  { city: 'Port Moresby', country: 'Papua New Guinea' },
  { city: 'Noumea', country: 'New Caledonia' },
  { city: 'Papeete', country: 'French Polynesia' },
  { city: 'Apia', country: 'Samoa' },
  { city: 'Nuku\'alofa', country: 'Tonga' },
  { city: 'Port Vila', country: 'Vanuatu' },
  { city: 'Honiara', country: 'Solomon Islands' },

  // MIDDLE EAST (additional)
  { city: 'Tehran', country: 'Iran' },
  { city: 'Baghdad', country: 'Iraq' },
  { city: 'Damascus', country: 'Syria' },
  { city: 'Muscat', country: 'Oman' },
  { city: 'Manama', country: 'Bahrain' },
  { city: 'Sanaa', country: 'Yemen' },
  { city: 'Kabul', country: 'Afghanistan' },
  { city: 'Mashhad', country: 'Iran' },
  { city: 'Isfahan', country: 'Iran' },
  { city: 'Tabriz', country: 'Iran' },
  { city: 'Shiraz', country: 'Iran' },
  { city: 'Basra', country: 'Iraq' },
  { city: 'Erbil', country: 'Iraq' },
  { city: 'Mosul', country: 'Iraq' },
  { city: 'Izmir', country: 'Turkey' },
  { city: 'Bursa', country: 'Turkey' },
  { city: 'Antalya', country: 'Turkey' },
  { city: 'Adana', country: 'Turkey' },
  { city: 'Gaziantep', country: 'Turkey' },
  { city: 'Konya', country: 'Turkey' },

  // RUSSIA (additional)
  { city: 'Novosibirsk', country: 'Russia' },
  { city: 'Yekaterinburg', country: 'Russia' },
  { city: 'Kazan', country: 'Russia' },
  { city: 'Nizhny Novgorod', country: 'Russia' },
  { city: 'Chelyabinsk', country: 'Russia' },
  { city: 'Samara', country: 'Russia' },
  { city: 'Omsk', country: 'Russia' },
  { city: 'Rostov-on-Don', country: 'Russia' },
  { city: 'Ufa', country: 'Russia' },
  { city: 'Krasnoyarsk', country: 'Russia' },
  { city: 'Voronezh', country: 'Russia' },
  { city: 'Perm', country: 'Russia' },
  { city: 'Volgograd', country: 'Russia' },
  { city: 'Vladivostok', country: 'Russia' },
  { city: 'Sochi', country: 'Russia' },

  // CHINA (additional major cities)
  { city: 'Hangzhou', country: 'China' },
  { city: 'Suzhou', country: 'China' },
  { city: 'Qingdao', country: 'China' },
  { city: 'Dalian', country: 'China' },
  { city: 'Zhengzhou', country: 'China' },
  { city: 'Changsha', country: 'China' },
  { city: 'Kunming', country: 'China' },
  { city: 'Jinan', country: 'China' },
  { city: 'Xiamen', country: 'China' },
  { city: 'Fuzhou', country: 'China' },
  { city: 'Hefei', country: 'China' },
  { city: 'Nanchang', country: 'China' },
  { city: 'Changchun', country: 'China' },
  { city: 'Harbin', country: 'China' },
  { city: 'Shijiazhuang', country: 'China' },
  { city: 'Taiyuan', country: 'China' },
  { city: 'Nanning', country: 'China' },
  { city: 'Guiyang', country: 'China' },
  { city: 'Urumqi', country: 'China' },
  { city: 'Lanzhou', country: 'China' },
  { city: 'Lhasa', country: 'China' },
  { city: 'Macau', country: 'China' },
  { city: 'Wenzhou', country: 'China' },
  { city: 'Ningbo', country: 'China' },
  { city: 'Wuxi', country: 'China' },
  { city: 'Foshan', country: 'China' },
  { city: 'Dongguan', country: 'China' },
  { city: 'Shenyang', country: 'China' },
  { city: 'Changzhou', country: 'China' },
  { city: 'Zhuhai', country: 'China' },
  { city: 'Yantai', country: 'China' },
  { city: 'Tangshan', country: 'China' },

  // INDIA (additional cities)
  { city: 'Visakhapatnam', country: 'India' },
  { city: 'Coimbatore', country: 'India' },
  { city: 'Kochi', country: 'India' },
  { city: 'Thiruvananthapuram', country: 'India' },
  { city: 'Madurai', country: 'India' },
  { city: 'Mysore', country: 'India' },
  { city: 'Mangalore', country: 'India' },
  { city: 'Nashik', country: 'India' },
  { city: 'Aurangabad', country: 'India' },
  { city: 'Rajkot', country: 'India' },
  { city: 'Varanasi', country: 'India' },
  { city: 'Agra', country: 'India' },
  { city: 'Amritsar', country: 'India' },
  { city: 'Chandigarh', country: 'India' },
  { city: 'Ludhiana', country: 'India' },
  { city: 'Jodhpur', country: 'India' },
  { city: 'Udaipur', country: 'India' },
  { city: 'Guwahati', country: 'India' },
  { city: 'Bhubaneswar', country: 'India' },
  { city: 'Ranchi', country: 'India' },
  { city: 'Raipur', country: 'India' },
  { city: 'Goa', country: 'India' },
  { city: 'Dehradun', country: 'India' },
  { city: 'Jalandhar', country: 'India' },
  { city: 'Allahabad', country: 'India' },
  { city: 'Meerut', country: 'India' },
  { city: 'Faridabad', country: 'India' },
  { city: 'Ghaziabad', country: 'India' },
  { city: 'Noida', country: 'India' },
  { city: 'Gurgaon', country: 'India' },

  // EUROPE (additional secondary cities)
  { city: 'Nottingham', country: 'United Kingdom' },
  { city: 'Leicester', country: 'United Kingdom' },
  { city: 'Coventry', country: 'United Kingdom' },
  { city: 'Bradford', country: 'United Kingdom' },
  { city: 'Reading', country: 'United Kingdom' },
  { city: 'Cambridge', country: 'United Kingdom' },
  { city: 'Oxford', country: 'United Kingdom' },
  { city: 'Southampton', country: 'United Kingdom' },
  { city: 'Portsmouth', country: 'United Kingdom' },
  { city: 'Brighton', country: 'United Kingdom' },
  { city: 'Plymouth', country: 'United Kingdom' },
  { city: 'Aberdeen', country: 'United Kingdom' },
  { city: 'Dundee', country: 'United Kingdom' },
  { city: 'Swansea', country: 'United Kingdom' },
  { city: 'Rennes', country: 'France' },
  { city: 'Reims', country: 'France' },
  { city: 'Le Havre', country: 'France' },
  { city: 'Saint-Etienne', country: 'France' },
  { city: 'Toulon', country: 'France' },
  { city: 'Grenoble', country: 'France' },
  { city: 'Dijon', country: 'France' },
  { city: 'Angers', country: 'France' },
  { city: 'Aix-en-Provence', country: 'France' },
  { city: 'Bonn', country: 'Germany' },
  { city: 'Mannheim', country: 'Germany' },
  { city: 'Karlsruhe', country: 'Germany' },
  { city: 'Wiesbaden', country: 'Germany' },
  { city: 'Augsburg', country: 'Germany' },
  { city: 'Bielefeld', country: 'Germany' },
  { city: 'Munster', country: 'Germany' },
  { city: 'Freiburg', country: 'Germany' },
  { city: 'Lubeck', country: 'Germany' },
  { city: 'Kiel', country: 'Germany' },
  { city: 'Mainz', country: 'Germany' },
  { city: 'Aachen', country: 'Germany' },
  { city: 'Rostock', country: 'Germany' },
  { city: 'Verona', country: 'Italy' },
  { city: 'Padua', country: 'Italy' },
  { city: 'Trieste', country: 'Italy' },
  { city: 'Brescia', country: 'Italy' },
  { city: 'Parma', country: 'Italy' },
  { city: 'Modena', country: 'Italy' },
  { city: 'Pisa', country: 'Italy' },
  { city: 'Bari', country: 'Italy' },
  { city: 'Catania', country: 'Italy' },
  { city: 'Messina', country: 'Italy' },
  { city: 'Alicante', country: 'Spain' },
  { city: 'Cordoba', country: 'Spain' },
  { city: 'Granada', country: 'Spain' },
  { city: 'Murcia', country: 'Spain' },
  { city: 'Palma', country: 'Spain' },
  { city: 'Las Palmas', country: 'Spain' },
  { city: 'Santa Cruz de Tenerife', country: 'Spain' },
  { city: 'San Sebastian', country: 'Spain' },
  { city: 'Santander', country: 'Spain' },
  { city: 'Oviedo', country: 'Spain' },
  { city: 'Gijon', country: 'Spain' },
  { city: 'A Coruna', country: 'Spain' },
  { city: 'Vigo', country: 'Spain' },
  { city: 'Braga', country: 'Portugal' },
  { city: 'Coimbra', country: 'Portugal' },
  { city: 'Funchal', country: 'Portugal' },
  { city: 'Katowice', country: 'Poland' },
  { city: 'Szczecin', country: 'Poland' },
  { city: 'Lublin', country: 'Poland' },
  { city: 'Bydgoszcz', country: 'Poland' },
  { city: 'Bialystok', country: 'Poland' },
  { city: 'Torun', country: 'Poland' },
  { city: 'Timisoara', country: 'Romania' },
  { city: 'Iasi', country: 'Romania' },
  { city: 'Constanta', country: 'Romania' },
  { city: 'Brno', country: 'Czech Republic' },
  { city: 'Ostrava', country: 'Czech Republic' },
  { city: 'Plzen', country: 'Czech Republic' },
  { city: 'Debrecen', country: 'Hungary' },
  { city: 'Szeged', country: 'Hungary' },
  { city: 'Pecs', country: 'Hungary' },
  { city: 'Plovdiv', country: 'Bulgaria' },
  { city: 'Varna', country: 'Bulgaria' },
  { city: 'Split', country: 'Croatia' },
  { city: 'Rijeka', country: 'Croatia' },
  { city: 'Dubrovnik', country: 'Croatia' },
  { city: 'Novi Sad', country: 'Serbia' },
  { city: 'Nis', country: 'Serbia' },
  { city: 'Maribor', country: 'Slovenia' },
  { city: 'Kosice', country: 'Slovakia' },
  { city: 'Kharkiv', country: 'Ukraine' },
  { city: 'Odesa', country: 'Ukraine' },
  { city: 'Dnipro', country: 'Ukraine' },
  { city: 'Lviv', country: 'Ukraine' },
  { city: 'Zaporizhzhia', country: 'Ukraine' },
  { city: 'Groningen', country: 'Netherlands' },
  { city: 'Tilburg', country: 'Netherlands' },
  { city: 'Breda', country: 'Netherlands' },
  { city: 'Nijmegen', country: 'Netherlands' },
  { city: 'Liege', country: 'Belgium' },
  { city: 'Charleroi', country: 'Belgium' },
  { city: 'Bruges', country: 'Belgium' },
  { city: 'Namur', country: 'Belgium' },
  { city: 'Linz', country: 'Austria' },
  { city: 'Klagenfurt', country: 'Austria' },
  { city: 'Uppsala', country: 'Sweden' },
  { city: 'Linkoping', country: 'Sweden' },
  { city: 'Orebro', country: 'Sweden' },
  { city: 'Vasteras', country: 'Sweden' },
  { city: 'Odense', country: 'Denmark' },
  { city: 'Aalborg', country: 'Denmark' },
  { city: 'Trondheim', country: 'Norway' },
  { city: 'Stavanger', country: 'Norway' },
  { city: 'Oulu', country: 'Finland' },
  { city: 'Espoo', country: 'Finland' },
  { city: 'Patras', country: 'Greece' },
  { city: 'Heraklion', country: 'Greece' },
  { city: 'Larissa', country: 'Greece' },
  { city: 'Limerick', country: 'Ireland' },
  { city: 'Waterford', country: 'Ireland' },
  { city: 'Winterthur', country: 'Switzerland' },
  { city: 'St Gallen', country: 'Switzerland' },
  { city: 'Lugano', country: 'Switzerland' },

  // NORTH AMERICA (additional Canadian and Mexican cities)
  { city: 'Mississauga', country: 'Canada' },
  { city: 'Brampton', country: 'Canada' },
  { city: 'Surrey', country: 'Canada' },
  { city: 'Laval', country: 'Canada' },
  { city: 'Markham', country: 'Canada' },
  { city: 'Vaughan', country: 'Canada' },
  { city: 'Gatineau', country: 'Canada' },
  { city: 'Burnaby', country: 'Canada' },
  { city: 'Richmond', country: 'Canada' },
  { city: 'Kelowna', country: 'Canada' },
  { city: 'Sherbrooke', country: 'Canada' },
  { city: 'St. John\'s', country: 'Canada' },
  { city: 'Barrie', country: 'Canada' },
  { city: 'Windsor', country: 'Canada' },
  { city: 'Oshawa', country: 'Canada' },
  { city: 'Oaxaca', country: 'Mexico' },
  { city: 'Veracruz', country: 'Mexico' },
  { city: 'Chihuahua', country: 'Mexico' },
  { city: 'Toluca', country: 'Mexico' },
  { city: 'Hermosillo', country: 'Mexico' },
  { city: 'Saltillo', country: 'Mexico' },
  { city: 'Morelia', country: 'Mexico' },
  { city: 'Queretaro', country: 'Mexico' },
  { city: 'Aguascalientes', country: 'Mexico' },
  { city: 'San Luis Potosi', country: 'Mexico' },
  { city: 'Culiacan', country: 'Mexico' },
  { city: 'Acapulco', country: 'Mexico' },
  { city: 'Mazatlan', country: 'Mexico' },
  { city: 'Tampico', country: 'Mexico' },
  { city: 'Cuernavaca', country: 'Mexico' },

  // SOUTH AMERICA (additional cities)
  { city: 'Manaus', country: 'Brazil' },
  { city: 'Belem', country: 'Brazil' },
  { city: 'Goiania', country: 'Brazil' },
  { city: 'Campinas', country: 'Brazil' },
  { city: 'Sao Luis', country: 'Brazil' },
  { city: 'Maceio', country: 'Brazil' },
  { city: 'Natal', country: 'Brazil' },
  { city: 'Joao Pessoa', country: 'Brazil' },
  { city: 'Teresina', country: 'Brazil' },
  { city: 'Campo Grande', country: 'Brazil' },
  { city: 'Santos', country: 'Brazil' },
  { city: 'Florianopolis', country: 'Brazil' },
  { city: 'Vitoria', country: 'Brazil' },
  { city: 'Ribeirao Preto', country: 'Brazil' },
  { city: 'Sorocaba', country: 'Brazil' },
  { city: 'Bucaramanga', country: 'Colombia' },
  { city: 'Cucuta', country: 'Colombia' },
  { city: 'Pereira', country: 'Colombia' },
  { city: 'Santa Marta', country: 'Colombia' },
  { city: 'Ibague', country: 'Colombia' },
  { city: 'Mar del Plata', country: 'Argentina' },
  { city: 'Tucuman', country: 'Argentina' },
  { city: 'Salta', country: 'Argentina' },
  { city: 'Santa Fe', country: 'Argentina' },
  { city: 'La Plata', country: 'Argentina' },
  { city: 'Neuquen', country: 'Argentina' },
  { city: 'Bahia Blanca', country: 'Argentina' },
  { city: 'Arequipa', country: 'Peru' },
  { city: 'Trujillo', country: 'Peru' },
  { city: 'Chiclayo', country: 'Peru' },
  { city: 'Piura', country: 'Peru' },
  { city: 'Cusco', country: 'Peru' },
  { city: 'Iquitos', country: 'Peru' },
  { city: 'Antofagasta', country: 'Chile' },
  { city: 'Temuco', country: 'Chile' },
  { city: 'Vina del Mar', country: 'Chile' },
  { city: 'Iquique', country: 'Chile' },
  { city: 'Talca', country: 'Chile' },
  { city: 'Puerto Montt', country: 'Chile' },
  { city: 'Punta Arenas', country: 'Chile' },
  { city: 'Cuenca', country: 'Ecuador' },
  { city: 'Machala', country: 'Ecuador' },
  { city: 'Loja', country: 'Ecuador' },
  { city: 'Manta', country: 'Ecuador' },
  { city: 'Maracaibo', country: 'Venezuela' },
  { city: 'Valencia', country: 'Venezuela' },
  { city: 'Barquisimeto', country: 'Venezuela' },
  { city: 'Maracay', country: 'Venezuela' },
  { city: 'Ciudad Guayana', country: 'Venezuela' },
  { city: 'Cochabamba', country: 'Bolivia' },
  { city: 'Sucre', country: 'Bolivia' },
  { city: 'Ciudad del Este', country: 'Paraguay' },
  { city: 'Punta del Este', country: 'Uruguay' },
  { city: 'Salto', country: 'Uruguay' },

  // AFRICA (additional cities)
  { city: 'Giza', country: 'Egypt' },
  { city: 'Luxor', country: 'Egypt' },
  { city: 'Aswan', country: 'Egypt' },
  { city: 'Port Said', country: 'Egypt' },
  { city: 'Suez', country: 'Egypt' },
  { city: 'Ismailia', country: 'Egypt' },
  { city: 'Mombasa', country: 'Kenya' },
  { city: 'Kisumu', country: 'Kenya' },
  { city: 'Nakuru', country: 'Kenya' },
  { city: 'Eldoret', country: 'Kenya' },
  { city: 'Zanzibar City', country: 'Tanzania' },
  { city: 'Mwanza', country: 'Tanzania' },
  { city: 'Arusha', country: 'Tanzania' },
  { city: 'Dodoma', country: 'Tanzania' },
  { city: 'Pietermaritzburg', country: 'South Africa' },
  { city: 'East London', country: 'South Africa' },
  { city: 'Port Elizabeth', country: 'South Africa' },
  { city: 'Bloemfontein', country: 'South Africa' },
  { city: 'Soweto', country: 'South Africa' },
  { city: 'Stellenbosch', country: 'South Africa' },
  { city: 'Tangier', country: 'Morocco' },
  { city: 'Agadir', country: 'Morocco' },
  { city: 'Meknes', country: 'Morocco' },
  { city: 'Oujda', country: 'Morocco' },
  { city: 'Kenitra', country: 'Morocco' },
  { city: 'Oran', country: 'Algeria' },
  { city: 'Constantine', country: 'Algeria' },
  { city: 'Annaba', country: 'Algeria' },
  { city: 'Sfax', country: 'Tunisia' },
  { city: 'Sousse', country: 'Tunisia' },
  { city: 'Kairouan', country: 'Tunisia' },
  { city: 'Kumasi', country: 'Ghana' },
  { city: 'Tamale', country: 'Ghana' },
  { city: 'Takoradi', country: 'Ghana' },
  { city: 'Enugu', country: 'Nigeria' },
  { city: 'Benin City', country: 'Nigeria' },
  { city: 'Kaduna', country: 'Nigeria' },
  { city: 'Jos', country: 'Nigeria' },
  { city: 'Ilorin', country: 'Nigeria' },
  { city: 'Aba', country: 'Nigeria' },
  { city: 'Onitsha', country: 'Nigeria' },
  { city: 'Warri', country: 'Nigeria' },
  { city: 'Dire Dawa', country: 'Ethiopia' },
  { city: 'Mekelle', country: 'Ethiopia' },
  { city: 'Gondar', country: 'Ethiopia' },
  { city: 'Bahir Dar', country: 'Ethiopia' },
  { city: 'Bulawayo', country: 'Zimbabwe' },
  { city: 'Mutare', country: 'Zimbabwe' },
  { city: 'Ndola', country: 'Zambia' },
  { city: 'Kitwe', country: 'Zambia' },
  { city: 'Livingstone', country: 'Zambia' },
  { city: 'Lubumbashi', country: 'Democratic Republic of the Congo' },
  { city: 'Mbuji-Mayi', country: 'Democratic Republic of the Congo' },
  { city: 'Kisangani', country: 'Democratic Republic of the Congo' },
  { city: 'Kananga', country: 'Democratic Republic of the Congo' },
  { city: 'Huambo', country: 'Angola' },
  { city: 'Lobito', country: 'Angola' },
  { city: 'Benguela', country: 'Angola' },
  { city: 'Beira', country: 'Mozambique' },
  { city: 'Nampula', country: 'Mozambique' },
  { city: 'Matola', country: 'Mozambique' },
  { city: 'Blantyre', country: 'Malawi' },
  { city: 'Mzuzu', country: 'Malawi' },
  { city: 'Francistown', country: 'Botswana' },
  { city: 'Maun', country: 'Botswana' },
  { city: 'Walvis Bay', country: 'Namibia' },
  { city: 'Swakopmund', country: 'Namibia' },
  { city: 'Toamasina', country: 'Madagascar' },
  { city: 'Antsirabe', country: 'Madagascar' },
  { city: 'Mahajanga', country: 'Madagascar' },
  { city: 'Fianarantsoa', country: 'Madagascar' },
  { city: 'Pointe-Noire', country: 'Republic of the Congo' },
  { city: 'Port-Gentil', country: 'Gabon' },
  { city: 'Franceville', country: 'Gabon' },
  { city: 'Hargeisa', country: 'Somalia' },
  { city: 'Berbera', country: 'Somalia' },
  { city: 'Thika', country: 'Kenya' },
  { city: 'Malindi', country: 'Kenya' },
  { city: 'Lamu', country: 'Kenya' },

  // MIDDLE EAST (additional cities)
  { city: 'Mecca', country: 'Saudi Arabia' },
  { city: 'Medina', country: 'Saudi Arabia' },
  { city: 'Dammam', country: 'Saudi Arabia' },
  { city: 'Khobar', country: 'Saudi Arabia' },
  { city: 'Taif', country: 'Saudi Arabia' },
  { city: 'Tabuk', country: 'Saudi Arabia' },
  { city: 'Sharjah', country: 'United Arab Emirates' },
  { city: 'Ajman', country: 'United Arab Emirates' },
  { city: 'Ras Al Khaimah', country: 'United Arab Emirates' },
  { city: 'Fujairah', country: 'United Arab Emirates' },
  { city: 'Al Ain', country: 'United Arab Emirates' },
  { city: 'Salalah', country: 'Oman' },
  { city: 'Sohar', country: 'Oman' },
  { city: 'Sur', country: 'Oman' },
  { city: 'Al Wakrah', country: 'Qatar' },
  { city: 'Al Khor', country: 'Qatar' },
  { city: 'Haifa', country: 'Israel' },
  { city: 'Eilat', country: 'Israel' },
  { city: 'Beer Sheva', country: 'Israel' },
  { city: 'Netanya', country: 'Israel' },
  { city: 'Aqaba', country: 'Jordan' },
  { city: 'Irbid', country: 'Jordan' },
  { city: 'Zarqa', country: 'Jordan' },
  { city: 'Tripoli', country: 'Lebanon' },
  { city: 'Sidon', country: 'Lebanon' },
  { city: 'Aleppo', country: 'Syria' },
  { city: 'Homs', country: 'Syria' },
  { city: 'Latakia', country: 'Syria' },

  // ASIA (additional secondary cities)
  { city: 'Yokohama', country: 'Japan' },
  { city: 'Chiba', country: 'Japan' },
  { city: 'Sagamihara', country: 'Japan' },
  { city: 'Hamamatsu', country: 'Japan' },
  { city: 'Niigata', country: 'Japan' },
  { city: 'Shizuoka', country: 'Japan' },
  { city: 'Okayama', country: 'Japan' },
  { city: 'Kumamoto', country: 'Japan' },
  { city: 'Kagoshima', country: 'Japan' },
  { city: 'Kanazawa', country: 'Japan' },
  { city: 'Naha', country: 'Japan' },
  { city: 'Matsuyama', country: 'Japan' },
  { city: 'Ulsan', country: 'South Korea' },
  { city: 'Seongnam', country: 'South Korea' },
  { city: 'Goyang', country: 'South Korea' },
  { city: 'Yongin', country: 'South Korea' },
  { city: 'Bucheon', country: 'South Korea' },
  { city: 'Suwon', country: 'South Korea' },
  { city: 'Ansan', country: 'South Korea' },
  { city: 'Jeju', country: 'South Korea' },
  { city: 'Hsinchu', country: 'Taiwan' },
  { city: 'Chiayi', country: 'Taiwan' },
  { city: 'Changhua', country: 'Taiwan' },
  { city: 'Pingtung', country: 'Taiwan' },
  { city: 'Semarang', country: 'Indonesia' },
  { city: 'Palembang', country: 'Indonesia' },
  { city: 'Tangerang', country: 'Indonesia' },
  { city: 'Depok', country: 'Indonesia' },
  { city: 'Bekasi', country: 'Indonesia' },
  { city: 'Batam', country: 'Indonesia' },
  { city: 'Bogor', country: 'Indonesia' },
  { city: 'Yogyakarta', country: 'Indonesia' },
  { city: 'Malang', country: 'Indonesia' },
  { city: 'Balikpapan', country: 'Indonesia' },
  { city: 'Denpasar', country: 'Indonesia' },
  { city: 'Pekanbaru', country: 'Indonesia' },
  { city: 'Pontianak', country: 'Indonesia' },
  { city: 'Manado', country: 'Indonesia' },
  { city: 'Caloocan', country: 'Philippines' },
  { city: 'Zamboanga City', country: 'Philippines' },
  { city: 'Taguig', country: 'Philippines' },
  { city: 'Pasig', country: 'Philippines' },
  { city: 'Antipolo', country: 'Philippines' },
  { city: 'Cagayan de Oro', country: 'Philippines' },
  { city: 'General Santos', country: 'Philippines' },
  { city: 'Iloilo City', country: 'Philippines' },
  { city: 'Bacolod', country: 'Philippines' },
  { city: 'George Town', country: 'Malaysia' },
  { city: 'Ipoh', country: 'Malaysia' },
  { city: 'Johor Bahru', country: 'Malaysia' },
  { city: 'Shah Alam', country: 'Malaysia' },
  { city: 'Petaling Jaya', country: 'Malaysia' },
  { city: 'Kota Kinabalu', country: 'Malaysia' },
  { city: 'Kuching', country: 'Malaysia' },
  { city: 'Malacca City', country: 'Malaysia' },
  { city: 'Chiang Mai', country: 'Thailand' },
  { city: 'Pattaya', country: 'Thailand' },
  { city: 'Phuket', country: 'Thailand' },
  { city: 'Hat Yai', country: 'Thailand' },
  { city: 'Nakhon Ratchasima', country: 'Thailand' },
  { city: 'Udon Thani', country: 'Thailand' },
  { city: 'Khon Kaen', country: 'Thailand' },
  { city: 'Da Nang', country: 'Vietnam' },
  { city: 'Hai Phong', country: 'Vietnam' },
  { city: 'Can Tho', country: 'Vietnam' },
  { city: 'Nha Trang', country: 'Vietnam' },
  { city: 'Hue', country: 'Vietnam' },
  { city: 'Bien Hoa', country: 'Vietnam' },
  { city: 'Vung Tau', country: 'Vietnam' },
  { city: 'Siem Reap', country: 'Cambodia' },
  { city: 'Sihanoukville', country: 'Cambodia' },
  { city: 'Battambang', country: 'Cambodia' },
  { city: 'Luang Prabang', country: 'Laos' },
  { city: 'Savannakhet', country: 'Laos' },
  { city: 'Mandalay', country: 'Myanmar' },
  { city: 'Naypyidaw', country: 'Myanmar' },
  { city: 'Mawlamyine', country: 'Myanmar' },
  { city: 'Multan', country: 'Pakistan' },
  { city: 'Hyderabad', country: 'Pakistan' },
  { city: 'Gujranwala', country: 'Pakistan' },
  { city: 'Sialkot', country: 'Pakistan' },
  { city: 'Bahawalpur', country: 'Pakistan' },
  { city: 'Sukkur', country: 'Pakistan' },
  { city: 'Pokhara', country: 'Nepal' },
  { city: 'Patan', country: 'Nepal' },
  { city: 'Biratnagar', country: 'Nepal' },
  { city: 'Kandy', country: 'Sri Lanka' },
  { city: 'Galle', country: 'Sri Lanka' },
  { city: 'Jaffna', country: 'Sri Lanka' },
  { city: 'Trincomalee', country: 'Sri Lanka' },
  { city: 'Dushanbe', country: 'Tajikistan' },
  { city: 'Bishkek', country: 'Kyrgyzstan' },
  { city: 'Osh', country: 'Kyrgyzstan' },
  { city: 'Ashgabat', country: 'Turkmenistan' },
  { city: 'Samarkand', country: 'Uzbekistan' },
  { city: 'Bukhara', country: 'Uzbekistan' },
  { city: 'Namangan', country: 'Uzbekistan' },
  { city: 'Andijan', country: 'Uzbekistan' },
  { city: 'Shymkent', country: 'Kazakhstan' },
  { city: 'Karaganda', country: 'Kazakhstan' },
  { city: 'Aktobe', country: 'Kazakhstan' },
  { city: 'Thimphu', country: 'Bhutan' },
  { city: 'Male', country: 'Maldives' },
  { city: 'Bandar Seri Begawan', country: 'Brunei' },
  { city: 'Dili', country: 'Timor-Leste' },

  // RUSSIA (additional cities)
  { city: 'Krasnodar', country: 'Russia' },
  { city: 'Saratov', country: 'Russia' },
  { city: 'Tyumen', country: 'Russia' },
  { city: 'Tolyatti', country: 'Russia' },
  { city: 'Izhevsk', country: 'Russia' },
  { city: 'Barnaul', country: 'Russia' },
  { city: 'Irkutsk', country: 'Russia' },
  { city: 'Ulyanovsk', country: 'Russia' },
  { city: 'Khabarovsk', country: 'Russia' },
  { city: 'Yaroslavl', country: 'Russia' },
  { city: 'Makhachkala', country: 'Russia' },
  { city: 'Tomsk', country: 'Russia' },
  { city: 'Orenburg', country: 'Russia' },
  { city: 'Kemerovo', country: 'Russia' },
  { city: 'Novokuznetsk', country: 'Russia' },
  { city: 'Ryazan', country: 'Russia' },
  { city: 'Astrakhan', country: 'Russia' },
  { city: 'Penza', country: 'Russia' },
  { city: 'Lipetsk', country: 'Russia' },
  { city: 'Tula', country: 'Russia' },
  { city: 'Kirov', country: 'Russia' },
  { city: 'Cheboksary', country: 'Russia' },
  { city: 'Kaliningrad', country: 'Russia' },
  { city: 'Kursk', country: 'Russia' },
  { city: 'Ulan-Ude', country: 'Russia' },
  { city: 'Magnitogorsk', country: 'Russia' },
  { city: 'Surgut', country: 'Russia' },
  { city: 'Nizhnevartovsk', country: 'Russia' },
  { city: 'Yakutsk', country: 'Russia' },
  { city: 'Petropavlovsk-Kamchatsky', country: 'Russia' },
  { city: 'Murmansk', country: 'Russia' },
  { city: 'Arkhangelsk', country: 'Russia' },
  { city: 'Grozny', country: 'Russia' },

  // OCEANIA (additional cities)
  { city: 'Geelong', country: 'Australia' },
  { city: 'Townsville', country: 'Australia' },
  { city: 'Cairns', country: 'Australia' },
  { city: 'Toowoomba', country: 'Australia' },
  { city: 'Ballarat', country: 'Australia' },
  { city: 'Bendigo', country: 'Australia' },
  { city: 'Launceston', country: 'Australia' },
  { city: 'Albury', country: 'Australia' },
  { city: 'Wollongong', country: 'Australia' },
  { city: 'Mackay', country: 'Australia' },
  { city: 'Rockhampton', country: 'Australia' },
  { city: 'Bunbury', country: 'Australia' },
  { city: 'Coffs Harbour', country: 'Australia' },
  { city: 'Mandurah', country: 'Australia' },
  { city: 'Tauranga', country: 'New Zealand' },
  { city: 'Napier', country: 'New Zealand' },
  { city: 'Palmerston North', country: 'New Zealand' },
  { city: 'Nelson', country: 'New Zealand' },
  { city: 'Rotorua', country: 'New Zealand' },
  { city: 'New Plymouth', country: 'New Zealand' },
  { city: 'Whangarei', country: 'New Zealand' },
  { city: 'Invercargill', country: 'New Zealand' },
  { city: 'Queenstown', country: 'New Zealand' },
  { city: 'Lautoka', country: 'Fiji' },
  { city: 'Nadi', country: 'Fiji' },
  { city: 'Lae', country: 'Papua New Guinea' },
  { city: 'Madang', country: 'Papua New Guinea' },
  { city: 'Rabaul', country: 'Papua New Guinea' },

  // CARIBBEAN (additional cities)
  { city: 'Santiago de Cuba', country: 'Cuba' },
  { city: 'Camaguey', country: 'Cuba' },
  { city: 'Holguin', country: 'Cuba' },
  { city: 'Varadero', country: 'Cuba' },
  { city: 'Santiago', country: 'Dominican Republic' },
  { city: 'La Romana', country: 'Dominican Republic' },
  { city: 'Puerto Plata', country: 'Dominican Republic' },
  { city: 'Punta Cana', country: 'Dominican Republic' },
  { city: 'Montego Bay', country: 'Jamaica' },
  { city: 'Ocho Rios', country: 'Jamaica' },
  { city: 'Spanish Town', country: 'Jamaica' },
  { city: 'Bridgetown', country: 'Barbados' },
  { city: 'Port of Spain', country: 'Trinidad and Tobago' },
  { city: 'San Fernando', country: 'Trinidad and Tobago' },
  { city: 'Willemstad', country: 'Curacao' },
  { city: 'Oranjestad', country: 'Aruba' },
  { city: 'Philipsburg', country: 'Sint Maarten' },
  { city: 'Castries', country: 'Saint Lucia' },
  { city: 'Saint George\'s', country: 'Grenada' },
  { city: 'Kingstown', country: 'Saint Vincent and the Grenadines' },
  { city: 'Roseau', country: 'Dominica' },
  { city: 'Saint John\'s', country: 'Antigua and Barbuda' },
  { city: 'Basseterre', country: 'Saint Kitts and Nevis' },
  { city: 'Road Town', country: 'British Virgin Islands' },
  { city: 'Charlotte Amalie', country: 'U.S. Virgin Islands' },
  { city: 'Hamilton', country: 'Bermuda' },
  { city: 'George Town', country: 'Cayman Islands' },
  { city: 'Belmopan', country: 'Belize' },
  { city: 'Belize City', country: 'Belize' },
];

interface PhotonFeature {
  geometry: {
    coordinates: [number, number];
  };
  properties: {
    osm_id?: number;
    osm_type?: string;
    osm_key?: string;
    osm_value?: string;
    name?: string;
    city?: string;
    state?: string;
    country?: string;
    countrycode?: string;
    type?: string;
  };
}

interface PhotonResponse {
  features: PhotonFeature[];
}

interface PhotonDocument {
  osm_id: number;
  osm_type: string;
  osm_key: string;
  osm_value: string;
  type: string;
  importance: number;
  name: { default: string; en?: string };
  coordinate: { lat: number; lon: number };
  countrycode: string;
  country?: { default: string };
  state?: { default: string };
  city?: { default: string };
  context: Record<string, unknown>;
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function geocodeCity(city: string, country: string): Promise<PhotonFeature | null> {
  const query = `${city}, ${country}`;
  const url = new URL(PHOTON_URL);
  url.searchParams.set('q', query);
  url.searchParams.set('limit', '1');
  url.searchParams.set('osm_tag', 'place');

  try {
    const response = await fetch(url.toString(), {
      headers: { 'User-Agent': 'Riftfound/1.0 (Top Cities Geocoder)' },
    });

    if (!response.ok) {
      console.error(`Geocode failed for "${query}": HTTP ${response.status}`);
      return null;
    }

    const data: PhotonResponse = await response.json();
    if (data.features.length === 0) {
      console.error(`No results for "${query}"`);
      return null;
    }

    return data.features[0];
  } catch (error) {
    console.error(`Geocode error for "${query}":`, error);
    return null;
  }
}

function featureToPhotonDocument(feature: PhotonFeature, docId: number, englishName: string): PhotonDocument {
  const props = feature.properties;
  const [lon, lat] = feature.geometry.coordinates;
  const osmValue = props.osm_value || props.type || 'city';

  // Use English name if the default name uses non-Latin characters
  const defaultName = props.name || '';
  const hasNonLatin = /[^\u0000-\u007F]/.test(defaultName);

  const doc: PhotonDocument = {
    osm_id: props.osm_id || docId,
    osm_type: props.osm_type?.charAt(0).toUpperCase() || 'N',
    osm_key: props.osm_key || 'place',
    osm_value: osmValue,
    type: osmValue,
    importance: 0.7, // Higher importance for major cities
    name: hasNonLatin
      ? { default: englishName, en: englishName }  // Use English as default for non-Latin
      : { default: defaultName },
    coordinate: { lat, lon },
    countrycode: (props.countrycode || '').toUpperCase(),
    context: {},
  };

  if (props.country) doc.country = { default: props.country };
  if (props.state) doc.state = { default: props.state };
  if (props.city && props.city !== props.name) doc.city = { default: props.city };

  return doc;
}

async function loadExistingOsmIds(filePath: string): Promise<Set<number>> {
  const ids = new Set<number>();
  try {
    const fs = await import('fs');
    const content = fs.readFileSync(filePath, 'utf-8');
    for (const line of content.split('\n')) {
      if (line.trim()) {
        const doc = JSON.parse(line);
        if (doc.osm_id) ids.add(doc.osm_id);
      }
    }
    console.error(`Loaded ${ids.size} existing osm_ids from ${filePath}`);
  } catch {
    console.error(`No existing file found at ${filePath}, will geocode all cities`);
  }
  return ids;
}

async function main() {
  const existingFile = process.argv[2] || '/tmp/cities.json';
  const existingIds = await loadExistingOsmIds(existingFile);

  console.error(`Processing ${TOP_CITIES.length} top world cities...`);

  let placeId = 800000000; // Different range from store cities
  let successCount = 0;
  let skipCount = 0;
  let failCount = 0;

  for (const { city, country } of TOP_CITIES) {
    console.error(`Geocoding: ${city}, ${country}...`);

    const feature = await geocodeCity(city, country);

    if (feature) {
      const osmId = feature.properties.osm_id;
      if (osmId && existingIds.has(osmId)) {
        console.error(`  Skipping (already exists): osm_id=${osmId}`);
        skipCount++;
      } else {
        const doc = featureToPhotonDocument(feature, placeId++, city);
        console.log(JSON.stringify(doc));
        successCount++;
        if (osmId) existingIds.add(osmId); // Prevent duplicates within this run
      }
    } else {
      failCount++;
    }

    await sleep(RATE_LIMIT_MS);
  }

  console.error(`\nDone! Added: ${successCount}, Skipped: ${skipCount}, Failed: ${failCount}`);
}

main().catch(console.error);
